### ISSUE TITLE
can't build on mac

### ISSUE THREAD

**Issue by ronnycsharp** [sothmann/typescript-gradle-plugin#11] opened 2015-04-29 12:00 UTC
Hi,
I have an issue and I hope you can help to solve the problem.

:compileTypeScript FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTypeScript'.
> A problem occurred starting process 'command 'tsc''

I' have installed typescript on OS X with npm install ..
My build.gradle file contains

sourceCompatibility = 1.6
targetCompatibility = 1.6

compileTypeScript {
    source = "src/main/webapp/ts"
    declaration = true
    sourcemap = false
    target = "ES5"
}

war {
    into("webapp/js") {
        from compileTypeScript.outputs
    }
}

**Comment by sothmann** [comment] 2015-04-29 17:45
Doesn't it give you more info on what went wrong?
Can you execute with --info or --stacktrace to get more info on the error?

It could be possible that it cannot find the "tsc" executable.
As a workaround you can define the exact location and name of "tsc" via the compilerExecutable option on the compileTypeScript task.

Please let me know if that helps.

**Comment by ronnycsharp** [comment] 2015-04-29 18:50
Hi, thanks for your answer. 
Could you please explain to me, how I could set the parameter in IntelliJ?
To get a detailed exception information. I am new to gradle.
At the Moment, I am starting the build-task in the gradle-view by double clicking.

thank you

**Comment by sothmann** [comment] 2015-04-30 05:56
In the Gradle view, press the Gradle icon on the top (labeled "Execute Gradle Task").
Then you can enter the Gradle command.
Try 
`compileTypeScript --info`
`compileTypeScript --debug`
or
`compileTypeScript --stacktrace`

and see if it gives you more details about what the problem is.

**Comment by ronnycsharp** [comment] 2015-04-30 06:27
Hi,
the command tsc was not found in my project directory.
But I've installed it globally with npm install -g typescript and I can run the tsc
in my terminal.

Is there anything I've forgotten?
Thanks for your help.

Regards
Ronny

**Comment by ronnycsharp** [comment] 2015-04-30 07:49
Caused by: java.io.IOException: Cannot run program "tsc" (in directory "/Users/ronny/Desktop/Projekte/MyWeb"): error=2, No such file or directory
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 3 more

**Comment by sothmann** [comment] 2015-04-30 09:03
Hm could be related to Mac OS.
Unfortunately I don't have access to a Mac.
You could try to point the compileTypeScript task to your tsc executable as follows:

```
compileTypeScript {
  compilerExecutable = "/path/to/your/tsc"
  source = "src/main/webapp/ts"
  declaration = true
  sourcemap = false
  target = "ES5"
}
```

On windows the tsc executable is located here:
`C:\Users\USERNAME\node_modules\typescript\bin\tsc`
You have to locate it on MacOS.

Please let me know if that works.

**Comment by sothmann** [comment] 2015-06-26 16:09
Closed as I got no further feedback. Feel free to reopen this issue if the problem persists.

**Closed by sothmann** 2015-06-26 16:09 UTC

**Comment by serrut** [comment] 2016-05-31 14:26
Hi,
I have the same problem as described above. Also on a mac.
When i use your last instructions, i get following error:

```
* What went wrong:
Execution failed for task ':compileTypeScript'.
> Process 'command '/usr/local/bin/tsc'' finished with non-zero exit value 127
```

**Comment by serrut** [comment] 2016-06-01 07:50
It seems to be an issue of the IDE (Idea) i'm using.
If i run the build script manually via the command line, i have no issues.

**Comment by sothmann** [comment] 2016-06-05 15:26
Hi @serrut,

in general, the plugin plays nicely with IntelliJ (I'm an IntelliJ user myself).
Unfortunately, I have no Mac available for testing, so I cannot check what's going wrong here.

I would think that the problems would disappear if you use the plugin in combination with the Node plugin, which is the recommended way of using the TypeScript Gradle plugin.

I just updated the README to show how to use it with the Node plugin, see
https://github.com/sothmann/typescript-gradle-plugin

Could you please try to use it with the Node plugin and let me know if that solves your problems?

Thanks in advance!

**Comment by serrut** [comment] 2016-06-06 08:30
That seems to do the trick!

Thank you for the update!

**Comment by sothmann** [comment] 2016-06-06 08:49
Glad it helped. Thanks for the feedback!
